<?php
/**
 * DataSourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QuantiModo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * quantimodo
 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.9
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QuantiModo\Client;

/**
 * DataSourceTest Class Doc Comment
 *
 * @category    Class
 * @description DataSource
 * @package     QuantiModo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DataSourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DataSource"
     */
    public function testDataSource()
    {
    }

    /**
     * Test attribute "affiliate"
     */
    public function testPropertyAffiliate()
    {
    }

    /**
     * Test attribute "background_color"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "buttons"
     */
    public function testPropertyButtons()
    {
    }

    /**
     * Test attribute "card"
     */
    public function testPropertyCard()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "connected"
     */
    public function testPropertyConnected()
    {
    }

    /**
     * Test attribute "connect_error"
     */
    public function testPropertyConnectError()
    {
    }

    /**
     * Test attribute "connect_instructions"
     */
    public function testPropertyConnectInstructions()
    {
    }

    /**
     * Test attribute "connector_id"
     */
    public function testPropertyConnectorId()
    {
    }

    /**
     * Test attribute "connect_status"
     */
    public function testPropertyConnectStatus()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "connector_client_id"
     */
    public function testPropertyConnectorClientId()
    {
    }

    /**
     * Test attribute "default_variable_category_name"
     */
    public function testPropertyDefaultVariableCategoryName()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "get_it_url"
     */
    public function testPropertyGetItUrl()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {
    }

    /**
     * Test attribute "image_html"
     */
    public function testPropertyImageHtml()
    {
    }

    /**
     * Test attribute "last_successful_updated_at"
     */
    public function testPropertyLastSuccessfulUpdatedAt()
    {
    }

    /**
     * Test attribute "last_update"
     */
    public function testPropertyLastUpdate()
    {
    }

    /**
     * Test attribute "linked_display_name_html"
     */
    public function testPropertyLinkedDisplayNameHtml()
    {
    }

    /**
     * Test attribute "long_description"
     */
    public function testPropertyLongDescription()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "mobile_connect_method"
     */
    public function testPropertyMobileConnectMethod()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "platforms"
     */
    public function testPropertyPlatforms()
    {
    }

    /**
     * Test attribute "premium"
     */
    public function testPropertyPremium()
    {
    }

    /**
     * Test attribute "scopes"
     */
    public function testPropertyScopes()
    {
    }

    /**
     * Test attribute "short_description"
     */
    public function testPropertyShortDescription()
    {
    }

    /**
     * Test attribute "spreadsheet_upload_link"
     */
    public function testPropertySpreadsheetUploadLink()
    {
    }

    /**
     * Test attribute "total_measurements_in_last_update"
     */
    public function testPropertyTotalMeasurementsInLastUpdate()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "update_requested_at"
     */
    public function testPropertyUpdateRequestedAt()
    {
    }

    /**
     * Test attribute "update_status"
     */
    public function testPropertyUpdateStatus()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }
}
