<?php
/**
 * GetStudyResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QuantiModo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * quantimodo
 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.100414
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QuantiModo\Client;

/**
 * GetStudyResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description GetStudyResponse
/**
 * @package     QuantiModo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetStudyResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetStudyResponse"
     */
    public function testGetStudyResponse()
    {
    }

    /**
     * Test attribute "cause_processed_daily_measurements"
     */
    public function testPropertyCauseProcessedDailyMeasurements()
    {
    }

    /**
     * Test attribute "cause_variable"
     */
    public function testPropertyCauseVariable()
    {
    }

    /**
     * Test attribute "charts"
     */
    public function testPropertyCharts()
    {
    }

    /**
     * Test attribute "data"
     */
    public function testPropertyData()
    {
    }

    /**
     * Test attribute "effect_processed_daily_measurements"
     */
    public function testPropertyEffectProcessedDailyMeasurements()
    {
    }

    /**
     * Test attribute "effect_variable"
     */
    public function testPropertyEffectVariable()
    {
    }

    /**
     * Test attribute "highcharts"
     */
    public function testPropertyHighcharts()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "pairs"
     */
    public function testPropertyPairs()
    {
    }

    /**
     * Test attribute "pairs_of_averages_for_all_users"
     */
    public function testPropertyPairsOfAveragesForAllUsers()
    {
    }

    /**
     * Test attribute "participant_instructions"
     */
    public function testPropertyParticipantInstructions()
    {
    }

    /**
     * Test attribute "statistics"
     */
    public function testPropertyStatistics()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {
    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "user_correlations"
     */
    public function testPropertyUserCorrelations()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user_study"
     */
    public function testPropertyUserStudy()
    {
    }
}
