<?php
/**
 * LocalDailyReminderNotificationTimesForAllReminderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QuantiModo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * quantimodo
 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.100414
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QuantiModo\Client;

/**
 * LocalDailyReminderNotificationTimesForAllReminderTest Class Doc Comment
 *
 * @category    Class */
// * @description LocalDailyReminderNotificationTimesForAllReminder
/**
 * @package     QuantiModo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocalDailyReminderNotificationTimesForAllReminderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LocalDailyReminderNotificationTimesForAllReminder"
     */
    public function testLocalDailyReminderNotificationTimesForAllReminder()
    {
    }

    /**
     * Test attribute "local_daily_reminder_notification_times_for_all_reminder"
     */
    public function testPropertyLocalDailyReminderNotificationTimesForAllReminder()
    {
    }
}
