<?php
/**
 * NotificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QuantiModo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * quantimodo
 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QuantiModo\Client;

/**
 * NotificationTest Class Doc Comment
 *
 * @category    Class */
// * @description Notification
/**
 * @package     QuantiModo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotificationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Notification"
     */
    public function testNotification()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "secondary_item_id"
     */
    public function testPropertySecondaryItemId()
    {
    }

    /**
     * Test attribute "component_name"
     */
    public function testPropertyComponentName()
    {
    }

    /**
     * Test attribute "component_action"
     */
    public function testPropertyComponentAction()
    {
    }

    /**
     * Test attribute "date_notified"
     */
    public function testPropertyDateNotified()
    {
    }

    /**
     * Test attribute "is_new"
     */
    public function testPropertyIsNew()
    {
    }

    /**
     * Test attribute "meta_data_array"
     */
    public function testPropertyMetaDataArray()
    {
    }
}
