<?php
/**
 * TrackingReminderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QuantiModo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * quantimodo
 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QuantiModo\Client;

/**
 * TrackingReminderTest Class Doc Comment
 *
 * @category    Class */
// * @description TrackingReminder
/**
 * @package     QuantiModo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TrackingReminderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TrackingReminder"
     */
    public function testTrackingReminder()
    {
    }

    /**
     * Test attribute "action_array"
     */
    public function testPropertyActionArray()
    {
    }

    /**
     * Test attribute "available_units"
     */
    public function testPropertyAvailableUnits()
    {
    }

    /**
     * Test attribute "client_id"
     */
    public function testPropertyClientId()
    {
    }

    /**
     * Test attribute "combination_operation"
     */
    public function testPropertyCombinationOperation()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "unit_abbreviated_name"
     */
    public function testPropertyUnitAbbreviatedName()
    {
    }

    /**
     * Test attribute "unit_category_id"
     */
    public function testPropertyUnitCategoryId()
    {
    }

    /**
     * Test attribute "unit_category_name"
     */
    public function testPropertyUnitCategoryName()
    {
    }

    /**
     * Test attribute "unit_id"
     */
    public function testPropertyUnitId()
    {
    }

    /**
     * Test attribute "unit_name"
     */
    public function testPropertyUnitName()
    {
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "filling_value"
     */
    public function testPropertyFillingValue()
    {
    }

    /**
     * Test attribute "first_daily_reminder_time"
     */
    public function testPropertyFirstDailyReminderTime()
    {
    }

    /**
     * Test attribute "frequency_text_description"
     */
    public function testPropertyFrequencyTextDescription()
    {
    }

    /**
     * Test attribute "frequency_text_description_with_time"
     */
    public function testPropertyFrequencyTextDescriptionWithTime()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "input_type"
     */
    public function testPropertyInputType()
    {
    }

    /**
     * Test attribute "instructions"
     */
    public function testPropertyInstructions()
    {
    }

    /**
     * Test attribute "ion_icon"
     */
    public function testPropertyIonIcon()
    {
    }

    /**
     * Test attribute "last_tracked"
     */
    public function testPropertyLastTracked()
    {
    }

    /**
     * Test attribute "last_value"
     */
    public function testPropertyLastValue()
    {
    }

    /**
     * Test attribute "latest_tracking_reminder_notification_reminder_time"
     */
    public function testPropertyLatestTrackingReminderNotificationReminderTime()
    {
    }

    /**
     * Test attribute "local_daily_reminder_notification_times"
     */
    public function testPropertyLocalDailyReminderNotificationTimes()
    {
    }

    /**
     * Test attribute "local_daily_reminder_notification_times_for_all_reminders"
     */
    public function testPropertyLocalDailyReminderNotificationTimesForAllReminders()
    {
    }

    /**
     * Test attribute "manual_tracking"
     */
    public function testPropertyManualTracking()
    {
    }

    /**
     * Test attribute "maximum_allowed_value"
     */
    public function testPropertyMaximumAllowedValue()
    {
    }

    /**
     * Test attribute "minimum_allowed_value"
     */
    public function testPropertyMinimumAllowedValue()
    {
    }

    /**
     * Test attribute "next_reminder_time_epoch_seconds"
     */
    public function testPropertyNextReminderTimeEpochSeconds()
    {
    }

    /**
     * Test attribute "notification_bar"
     */
    public function testPropertyNotificationBar()
    {
    }

    /**
     * Test attribute "number_of_raw_measurements"
     */
    public function testPropertyNumberOfRawMeasurements()
    {
    }

    /**
     * Test attribute "number_of_unique_values"
     */
    public function testPropertyNumberOfUniqueValues()
    {
    }

    /**
     * Test attribute "outcome"
     */
    public function testPropertyOutcome()
    {
    }

    /**
     * Test attribute "png_path"
     */
    public function testPropertyPngPath()
    {
    }

    /**
     * Test attribute "png_url"
     */
    public function testPropertyPngUrl()
    {
    }

    /**
     * Test attribute "pop_up"
     */
    public function testPropertyPopUp()
    {
    }

    /**
     * Test attribute "reminder_end_time"
     */
    public function testPropertyReminderEndTime()
    {
    }

    /**
     * Test attribute "reminder_frequency"
     */
    public function testPropertyReminderFrequency()
    {
    }

    /**
     * Test attribute "reminder_sound"
     */
    public function testPropertyReminderSound()
    {
    }

    /**
     * Test attribute "reminder_start_epoch_seconds"
     */
    public function testPropertyReminderStartEpochSeconds()
    {
    }

    /**
     * Test attribute "reminder_start_time"
     */
    public function testPropertyReminderStartTime()
    {
    }

    /**
     * Test attribute "reminder_start_time_local"
     */
    public function testPropertyReminderStartTimeLocal()
    {
    }

    /**
     * Test attribute "reminder_start_time_local_human_formatted"
     */
    public function testPropertyReminderStartTimeLocalHumanFormatted()
    {
    }

    /**
     * Test attribute "repeating"
     */
    public function testPropertyRepeating()
    {
    }

    /**
     * Test attribute "second_daily_reminder_time"
     */
    public function testPropertySecondDailyReminderTime()
    {
    }

    /**
     * Test attribute "second_to_last_value"
     */
    public function testPropertySecondToLastValue()
    {
    }

    /**
     * Test attribute "sms"
     */
    public function testPropertySms()
    {
    }

    /**
     * Test attribute "start_tracking_date"
     */
    public function testPropertyStartTrackingDate()
    {
    }

    /**
     * Test attribute "stop_tracking_date"
     */
    public function testPropertyStopTrackingDate()
    {
    }

    /**
     * Test attribute "svg_url"
     */
    public function testPropertySvgUrl()
    {
    }

    /**
     * Test attribute "third_daily_reminder_time"
     */
    public function testPropertyThirdDailyReminderTime()
    {
    }

    /**
     * Test attribute "third_to_last_value"
     */
    public function testPropertyThirdToLastValue()
    {
    }

    /**
     * Test attribute "tracking_reminder_id"
     */
    public function testPropertyTrackingReminderId()
    {
    }

    /**
     * Test attribute "tracking_reminder_image_url"
     */
    public function testPropertyTrackingReminderImageUrl()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "user_variable_unit_abbreviated_name"
     */
    public function testPropertyUserVariableUnitAbbreviatedName()
    {
    }

    /**
     * Test attribute "user_variable_unit_category_id"
     */
    public function testPropertyUserVariableUnitCategoryId()
    {
    }

    /**
     * Test attribute "user_variable_unit_category_name"
     */
    public function testPropertyUserVariableUnitCategoryName()
    {
    }

    /**
     * Test attribute "user_variable_unit_id"
     */
    public function testPropertyUserVariableUnitId()
    {
    }

    /**
     * Test attribute "user_variable_unit_name"
     */
    public function testPropertyUserVariableUnitName()
    {
    }

    /**
     * Test attribute "user_variable_variable_category_id"
     */
    public function testPropertyUserVariableVariableCategoryId()
    {
    }

    /**
     * Test attribute "user_variable_variable_category_name"
     */
    public function testPropertyUserVariableVariableCategoryName()
    {
    }

    /**
     * Test attribute "valence"
     */
    public function testPropertyValence()
    {
    }

    /**
     * Test attribute "value_and_frequency_text_description"
     */
    public function testPropertyValueAndFrequencyTextDescription()
    {
    }

    /**
     * Test attribute "value_and_frequency_text_description_with_time"
     */
    public function testPropertyValueAndFrequencyTextDescriptionWithTime()
    {
    }

    /**
     * Test attribute "variable_category_id"
     */
    public function testPropertyVariableCategoryId()
    {
    }

    /**
     * Test attribute "variable_category_image_url"
     */
    public function testPropertyVariableCategoryImageUrl()
    {
    }

    /**
     * Test attribute "variable_category_name"
     */
    public function testPropertyVariableCategoryName()
    {
    }

    /**
     * Test attribute "variable_description"
     */
    public function testPropertyVariableDescription()
    {
    }

    /**
     * Test attribute "variable_id"
     */
    public function testPropertyVariableId()
    {
    }

    /**
     * Test attribute "variable_name"
     */
    public function testPropertyVariableName()
    {
    }
}
