<?php
/**
 * UnitTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  QuantiModo\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * quantimodo
 *
 * We make it easy to retrieve and analyze normalized user data from a wide array of devices and applications. Check out our [docs and sdk's](https://github.com/QuantiModo/docs) or [contact us](https://help.quantimo.do).
 *
 * OpenAPI spec version: 5.8.112511
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace QuantiModo\Client;

/**
 * UnitTest Class Doc Comment
 *
 * @category    Class */
// * @description Unit
/**
 * @package     QuantiModo\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UnitTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Unit"
     */
    public function testUnit()
    {
    }

    /**
     * Test attribute "abbreviated_name"
     */
    public function testPropertyAbbreviatedName()
    {
    }

    /**
     * Test attribute "advanced"
     */
    public function testPropertyAdvanced()
    {
    }

    /**
     * Test attribute "category"
     */
    public function testPropertyCategory()
    {
    }

    /**
     * Test attribute "category_id"
     */
    public function testPropertyCategoryId()
    {
    }

    /**
     * Test attribute "category_name"
     */
    public function testPropertyCategoryName()
    {
    }

    /**
     * Test attribute "conversion_steps"
     */
    public function testPropertyConversionSteps()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "manual_tracking"
     */
    public function testPropertyManualTracking()
    {
    }

    /**
     * Test attribute "maximum_allowed_value"
     */
    public function testPropertyMaximumAllowedValue()
    {
    }

    /**
     * Test attribute "maximum_value"
     */
    public function testPropertyMaximumValue()
    {
    }

    /**
     * Test attribute "minimum_allowed_value"
     */
    public function testPropertyMinimumAllowedValue()
    {
    }

    /**
     * Test attribute "minimum_value"
     */
    public function testPropertyMinimumValue()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "unit_category"
     */
    public function testPropertyUnitCategory()
    {
    }
}
